### ISSUE TITLE
Memory Leak on GetSerialPortNames

### ISSUE THREAD

**Issue by bpranoto** [JurassicPork/TLazSerial#3]
Hi,

There is a memory leak on function GetSerialPortNames on unit LazSynaSer.

In that function local variable sr:TSearchRec is closed on the end of the function:
```
  try
    TmpPorts := '';
    ScanForPorts( '/dev/rfcomm*',true);
 //   ScanForPorts( '/dev/pts/*');
    ScanForPorts( '/dev/ttyUSB*',true);
    ScanForPorts( '/dev/ttyS*',false);
    ScanForPorts( '/dev/ttyAM*',true); // for ARM board
    FindClose(sr);  // <= WRONG PLACE
```
This causes a memory leak, after some research I found this link [https://www.freepascal.org/docs-html/rtl/sysutils/findfirst.html](https://www.freepascal.org/docs-html/rtl/sysutils/findfirst.html) FindClose() should be called whenever FindFirst succeed. This means FindClose() should be placed inside the sub procedure ScanForPorts()

```
procedure ScanForPorts( const ThisRootStr : string; special :  boolean); // added by PDF
  var theDevice : String;
  var FD : Cint;
  var Ser : TSerialStruct;
  begin
    if FindFirst( ThisRootStr, $FFFFFFFF, sr) = 0 then
    begin
      repeat
      ......
      until FindNext(sr) <> 0;
      FindClose(sr); // <== FindClose() should be placed here
    end;
  end;       
```
After modifying this function, the memory leak is gone.

Attached is my patch to correct the problem

Thank you
[fix_memory_leak_on_get_serial_port_names.diff.txt](https://github.com/JurassicPork/TLazSerial/files/6122069/fix_memory_leak_on_get_serial_port_names.diff.txt)

**Comment by JurassicPork** [comment]
Ok thanks bpranoto, the fix has been applied in lazsynaser.pas
