### ISSUE TITLE
Changes upstreamed to Synapse

### ISSUE THREAD

**Issue by JonnyTech** [JurassicPork/TLazSerial#5]
Hello, have the changes to `synaser`, especially those for MacOS, been upstreamed back to the Synapse project?

**Comment by JurassicPork** [comment]
hello,
sorry for the late response -> no, if you have issue with synaser on MacOs , contact the author of synaser.

**Comment by JonnyTech** [comment]
Ah, ok. Thanks. I had found that your changes were the only ones that worked at the time. But I no longer have the device so can not test anymore. Otherwise I would contact the author and submit your modifications. I just did not want to appear to be passing off your work as mine.
