### ISSUE TITLE
TLazSerial does not return string

### ISSUE THREAD

**Issue by oliverhbailey** [JurassicPork/TLazSerial#7]
Hello,
The only way to get the serial port list in Free Pascal 3.2.2 with Lazarus 2.3.0 is to define an ansistring.  But even with that an error is generated that GetSerialPortNames is not a member of any class that will return a string.  Looking at the ancestor class TBlockSerial, the same problem exists and there is no detailed documentation or examples of this procedures use.  Is there anywhere an example use of this can be found?

**Comment by sstvmaster** [comment]
Hi,
this has been discussed here before: https://forum.lazarus.freepascal.org/index.php?topic=35667.0

GetSerialPortNames returns comma separated strings, eg: 'COM1,COM3,COM33'. With this you can put this into a ComboBox.

**Comment by oliverhbailey** [comment]
Thank you.
After I sent that request, I found further information in lazsynaser and
setupdialog units.  Its been a few years since I worked with Lazarus, so I
attempting to remove the rust from this old piece of metal.

Thank you again.

Regards,
Oliver Bailey
