### ISSUE TITLE
Error...Unknown property: "NonBlock" in Win10

### ISSUE THREAD

**Issue by VE2ZAZ** [JurassicPork/TLazSerial#9]
Hi,

I am compiling a piece of software that uses your great TLazSerial 0.6.0.0 package. I installed the package in Lazarus IDE v2.2.6, in both Linux Xubuntu 20.04 and Windows 10. Everything is working fine in Linux. However, when I compile my same code in Windows 10, I get the following error:  "Error reading LazSerial.SynSer.NonBlock: Unknown property: "NonBlock"".

I understand that this property is not applicable to Windows, and indeed it does not show up as a property in the Object Inspector. And  my software code does not touch that property. Yet, I get the error message.

Can you explain what is happening? Do you have a workaround?

Thanks in advance for your help.

Bert.

**Comment by JurassicPork** [comment]
Hello,
NonBlock is only for unix system, try to see if you have a NonBlock property defined in your lfm  form file. Remove it on windows.
Friendly, J.P
